services:
  backend:
    build:
      context: .
      dockerfile: backend/Dockerfile
      env_file:
        - ./backend/.env
    ports:
      - "6699:6699"
    volumes:
      #   - ./backend:/app
      - /app/node_modules
      - /app/backend/node_modules

  frontend:
    build:
      context: .
      dockerfile: frontend/Dockerfile
      env_file:
        - ./frontend/.env
    ports:
      - "6700:6700"
    volumes:
      #   - ./frontend:/app
      - /app/node_modules
      - /app/frontend/node_modules
    depends_on:
      - backend

  test-app:
    build:
      context: .
      dockerfile: test-app/Dockerfile
      env_file:
        - ./test-app/.env
    volumes:
      #   - ./test-app:/app
      - /app/node_modules
      - /app/test-app/node_modules
    depends_on:
      - backend
      - frontend
