services:
  frontend:
    build:
      context: .
      dockerfile: frontend/Dockerfile
    ports:
      - "6700:6700"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    depends_on:
      - backend

  backend:
    build:
      context: .
      dockerfile: backend/Dockerfile
    ports:
      - "6699:6699"
    volumes:
      - ./backend:/app
      - /app/node_modules

  test-app:
    build:
      context: .
      dockerfile: test-app/Dockerfile
    volumes:
      - ./test-app:/app
      - /app/node_modules
    # You can add any setup steps here when you need the test-app to run
